# Form implementation generated from reading ui file 'rocketGUI.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget, plot
from PyQt6.QtCore import QTimer
import numpy as np


class Ui_MainWindow(object):
    def __init__(self):
        self.data_list = None
        self.timer = QTimer()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plot = PlotWidget(self.centralwidget)
        self.plot.setGeometry(QtCore.QRect(20, -10, 761, 321))
        self.plot.setObjectName("plot")
        self.open_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_button.setGeometry(QtCore.QRect(540, 320, 141, 51))
        self.open_button.setObjectName("open_button")
        self.file_name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.file_name_input.setGeometry(QtCore.QRect(220, 330, 301, 31))
        self.file_name_input.setObjectName("file_name_input")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open_button.setText(_translate("MainWindow", "Open"))
        self.file_name_input.setText(_translate("MainWindow", "file name here"))
        self.open_button.clicked.connect(self.open_button_handler)

    
    def open_button_handler(self):
        #filename = self.file_name_input.text()
        #path = filename
        #print('clicked')

        with open('/Users/dharmikpatel/Downloads/launch_example.csv', "r") as f:
            self.data_list = f.readlines()
            self.data_list = self.data_list[1:]



    def reaTimePLot(self):
        self.timer.setInterval(500)
        info = [x.split(',') for x in self.data_list]
        for data in info:
            time = float(data[0])
            altitude = float(data[1])
            plot1 = plot.plot()






if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
